# conda config --set channel_priority true
name: blaze
channels:
  - bioconda
  - default
  - conda-forge
dependencies:
  - python=3.7
  - Biopython
  - pandas
  # - pysam
  - numpy
  - tqdm
  - matplotlib
  - kneed
  # - intervaltree
  # - scipy
  # - scikit-image
  # - pip
  # - pip:
  #   - tables